/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        white: 'rgb(var(--c-white) / <alpha-value>)',
        black: 'rgb(var(--c-black) / <alpha-value>)',
        void: {
          950: 'rgb(var(--c-void-950) / <alpha-value>)',
          900: 'rgb(var(--c-void-900) / <alpha-value>)',
          800: 'rgb(var(--c-void-800) / <alpha-value>)',
          700: 'rgb(var(--c-void-700) / <alpha-value>)',
          600: 'rgb(var(--c-void-600) / <alpha-value>)',
          500: 'rgb(var(--c-void-500) / <alpha-value>)',
        },
        arcane: {
          DEFAULT: 'rgb(var(--c-arcane) / <alpha-value>)',
          50: 'rgb(var(--c-arcane-50) / <alpha-value>)',
          100: 'rgb(var(--c-arcane-100) / <alpha-value>)',
          200: 'rgb(var(--c-arcane-200) / <alpha-value>)',
          300: 'rgb(var(--c-arcane-300) / <alpha-value>)',
          400: 'rgb(var(--c-arcane-400) / <alpha-value>)',
          500: 'rgb(var(--c-arcane-500) / <alpha-value>)',
          600: 'rgb(var(--c-arcane-600) / <alpha-value>)',
          700: 'rgb(var(--c-arcane-700) / <alpha-value>)',
        },
        gold: {
          DEFAULT: 'rgb(var(--c-gold) / <alpha-value>)',
          300: 'rgb(var(--c-gold-300) / <alpha-value>)',
          400: 'rgb(var(--c-gold-400) / <alpha-value>)',
          500: 'rgb(var(--c-gold-500) / <alpha-value>)',
          600: 'rgb(var(--c-gold-600) / <alpha-value>)',
          700: 'rgb(var(--c-gold-700) / <alpha-value>)',
        },
        slate: {
          DEFAULT: 'rgb(var(--c-slate) / <alpha-value>)',
          50: 'rgb(var(--c-slate-50) / <alpha-value>)',
          100: 'rgb(var(--c-slate-100) / <alpha-value>)',
          200: 'rgb(var(--c-slate-200) / <alpha-value>)',
          300: 'rgb(var(--c-slate-300) / <alpha-value>)',
          400: 'rgb(var(--c-slate-400) / <alpha-value>)',
          500: 'rgb(var(--c-slate-500) / <alpha-value>)',
          600: 'rgb(var(--c-slate-600) / <alpha-value>)',
          700: 'rgb(var(--c-slate-700) / <alpha-value>)',
          800: 'rgb(var(--c-slate-800) / <alpha-value>)',
          900: 'rgb(var(--c-slate-900) / <alpha-value>)',
          950: 'rgb(var(--c-slate-950) / <alpha-value>)',
        },
        emerald: {
          DEFAULT: 'rgb(var(--c-emerald) / <alpha-value>)',
          100: 'rgb(var(--c-emerald-100) / <alpha-value>)',
          200: 'rgb(var(--c-emerald-200) / <alpha-value>)',
          300: 'rgb(var(--c-emerald-300) / <alpha-value>)',
          400: 'rgb(var(--c-emerald-400) / <alpha-value>)',
          500: 'rgb(var(--c-emerald-500) / <alpha-value>)',
          600: 'rgb(var(--c-emerald-600) / <alpha-value>)',
          700: 'rgb(var(--c-emerald-700) / <alpha-value>)',
        },
        rose: {
          DEFAULT: 'rgb(var(--c-rose) / <alpha-value>)',
          100: 'rgb(var(--c-rose-100) / <alpha-value>)',
          200: 'rgb(var(--c-rose-200) / <alpha-value>)',
          300: 'rgb(var(--c-rose-300) / <alpha-value>)',
          400: 'rgb(var(--c-rose-400) / <alpha-value>)',
          500: 'rgb(var(--c-rose-500) / <alpha-value>)',
          600: 'rgb(var(--c-rose-600) / <alpha-value>)',
          700: 'rgb(var(--c-rose-700) / <alpha-value>)',
        },
        amber: {
          DEFAULT: 'rgb(var(--c-amber) / <alpha-value>)',
          100: 'rgb(var(--c-amber-100) / <alpha-value>)',
          200: 'rgb(var(--c-amber-200) / <alpha-value>)',
          300: 'rgb(var(--c-amber-300) / <alpha-value>)',
          400: 'rgb(var(--c-amber-400) / <alpha-value>)',
          500: 'rgb(var(--c-amber-500) / <alpha-value>)',
          600: 'rgb(var(--c-amber-600) / <alpha-value>)',
          700: 'rgb(var(--c-amber-700) / <alpha-value>)',
        },
        sky: {
          DEFAULT: 'rgb(var(--c-sky) / <alpha-value>)',
          100: 'rgb(var(--c-sky-100) / <alpha-value>)',
          200: 'rgb(var(--c-sky-200) / <alpha-value>)',
          300: 'rgb(var(--c-sky-300) / <alpha-value>)',
          400: 'rgb(var(--c-sky-400) / <alpha-value>)',
          500: 'rgb(var(--c-sky-500) / <alpha-value>)',
          600: 'rgb(var(--c-sky-600) / <alpha-value>)',
          700: 'rgb(var(--c-sky-700) / <alpha-value>)',
        },
      },
      fontFamily: {
        display: ['"DM Serif Display"', 'Georgia', 'serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        hand: ['"Patrick Hand"', 'cursive'],
      },
      boxShadow: {
        glow: '0 0 24px -4px rgb(var(--c-arcane-500) / 0.5)',
        gold: '0 0 24px -4px rgb(var(--c-gold-500) / 0.55)',
        panel: '0 1px 0 0 rgb(var(--c-slate-50) / 0.045) inset, 0 18px 40px -22px rgb(0 0 0 / 0.75)',
        lamp: '0 0 42px 6px rgb(var(--c-gold-500) / 0.16), 0 0 90px 20px rgb(var(--c-gold-500) / 0.07)',
      },
      backgroundImage: {
        'void-radial':
          'radial-gradient(1100px 600px at 15% -5%, rgb(var(--glow-accent) / 0.16), transparent 60%), radial-gradient(1000px 500px at 100% 0%, rgb(var(--glow-gold) / 0.08), transparent 55%), radial-gradient(800px 500px at 50% 120%, rgb(var(--glow-sage) / 0.06), transparent 60%)',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-14px)' },
        },
        'pulse-glow': {
          '0%, 100%': { opacity: '0.6', transform: 'scale(1)' },
          '50%': { opacity: '1', transform: 'scale(1.06)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        flicker: {
          '0%, 100%': { opacity: '0.9' },
          '7%': { opacity: '0.72' },
          '11%': { opacity: '0.96' },
          '34%': { opacity: '0.82' },
          '41%': { opacity: '0.98' },
          '66%': { opacity: '0.86' },
          '82%': { opacity: '0.94' },
        },
        steam: {
          '0%': { transform: 'translateY(0) translateX(0) scaleX(1)', opacity: '0' },
          '25%': { opacity: '0.5' },
          '100%': { transform: 'translateY(-34px) translateX(5px) scaleX(1.9)', opacity: '0' },
        },
      },
      animation: {
        float: 'float 7s ease-in-out infinite',
        'pulse-glow': 'pulse-glow 2.4s ease-in-out infinite',
        shimmer: 'shimmer 1.8s linear infinite',
        flicker: 'flicker 6s ease-in-out infinite',
        steam: 'steam 3.4s ease-in-out infinite',
      },
    },
  },
  plugins: [],
};